export const languageOptions = [
    { value: "hindi", label: "Hindi" },
    { value: "english", label: "English" },
    { value: "marathi", label: "Marathi" },
    { value: "urdu", label: "Urdu" },
    { value: "spanish", label: "Spanish" },
    { value: "german", label: "German" },
  ];
  
  export const bookCategoryOptions = [
    { value: "science-fiction", label: "Science Fiction" },
    { value: "fantasy", label: "Fantasy" },
    { value: "mystery", label: "Mystery" },
    { value: "romance", label: "Romance" },
    { value: "horror", label: "Horror" },
    { value: "historical-fiction", label: "Historical Fiction" },
    { value: "thriller", label: "Thriller" },
    { value: "adventure", label: "Adventure" },
    { value: "biography", label: "Biography" },
    { value: "self-help", label: "Self-Help" },
    { value: "cooking", label: "Cooking" },
    { value: "travel", label: "Travel" },
    { value: "science", label: "Science" },
    { value: "psychology", label: "Psychology" },
    { value: "philosophy", label: "Philosophy" },
    { value: "poetry", label: "Poetry" },
    { value: "art", label: "Art" },
    { value: "children", label: "Children's Literature" },
    { value: "drama", label: "Drama" },
    { value: "comics", label: "Comics" },
    { value: "graphic-novels", label: "Graphic Novels" },
    { value: "mythology", label: "Mythology" },
    { value: "religion", label: "Religion" },
    { value: "health-wellness", label: "Health & Wellness" },
    { value: "business", label: "Business" },
    { value: "politics", label: "Politics" },
    { value: "law", label: "Law" },
    { value: "education", label: "Education" },
    { value: "environment", label: "Environment" },
    { value: "sports", label: "Sports" },
    { value: "technology", label: "Technology" },
    { value: "music", label: "Music" },
    { value: "true-crime", label: "True Crime" },
    { value: "short-stories", label: "Short Stories" },
    { value: "essays", label: "Essays" },
    { value: "memoir", label: "Memoir" },
    { value: "satire", label: "Satire" },
    { value: "young-adult", label: "Young Adult" },
  ];
  